#!/bin/sh
#
#  This script places the new systems hostname into a couple of files within
# the new image.
#
# Steve
# --
# https://steve.fi/



prefix=$1


#
#  Source our common functions
#

if [ -e /usr/share/vm-deploy/common.sh ]; then
    . /usr/share/vm-deploy/common.sh
else
    . "${HOOK_DIR}/common.sh"
fi


#
# Log our start
#
log_msg info "Script $0 starting"

#
#  Determine the FQDN and Hostname
#
GUEST_FQDN=${hostname}
GUEST_HOSTNAME=`echo $GUEST_FQDN | awk -F'.' '{print $1}'`


#
#  Make sure the umask is correct
#
umask 022


#
#  Setup the mailname + hostname files.
#
echo $GUEST_HOSTNAME > ${prefix}/etc/hostname
echo $GUEST_FQDN > ${prefix}/etc/mailname


#
#  Fixup the /etc/hosts file upon the new image for
# machines with static IPs
#
if [ -z "${copyhosts}" ]; then
    #
    #  Copy localhost
    #
    cat > ${prefix}/etc/hosts <<EOF
127.0.0.1	localhost
EOF
    #
    #  Make sure our hostname and FQDN is resolvable
    #
    if [ -z "${dhcp}" ]; then
        #
        #  If DHCP is disabled, FQDN should resolve to our IP
        #
        cat >> ${prefix}/etc/hosts <<EOF
${ip}	$GUEST_FQDN $GUEST_HOSTNAME
EOF
    else
        cat >> ${prefix}/etc/hosts <<EOF
127.0.1.1	$GUEST_FQDN $GUEST_HOSTNAME
EOF
    fi

    cat >> ${prefix}/etc/hosts <<EOF
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters

EOF

else
    # Non-IPv6 stuff.
    grep -v '\(::\|IPv6\)' /etc/hosts > ${prefix}/etc/hosts

    # New entry.
    if [ -z "${dhcp}" ]; then
        cat >> ${prefix}/etc/hosts <<EOF
${ip}	$GUEST_FQDN $GUEST_HOSTNAME

EOF
    else
    cat >> ${prefix}/etc/hosts <<EOF
127.0.1.1	$GUEST_FQDN $GUEST_HOSTNAME

EOF
    fi

    # IPv6 stuff.
    grep '\(::\|IPv6\)' /etc/hosts >> ${prefix}/etc/hosts
fi


#
#  Allow the host system to know the IP address of our new guest.
#
if [ -z "${dhcp}" ]; then

    if ( grep $GUEST_FQDN /etc/hosts > /dev/null ) ; then

        log_msg warn "Host already has IP address for the host $GUEST_FQDN."

    else
        if [ "${nohosts}" = 0 ]; then

            log_msg info "Adding $GUEST_FQDN and $GUEST_HOSTNAME to /etc/hosts on the host"
            echo "${ip}    $GUEST_FQDN $GUEST_HOSTNAME" >> /etc/hosts

            #
            #  If we've updated the /etc/hosts file on the host machine
            # and there is an installation of dnsmasq installed then
            # reload it.
            #
            #  This will let the local LAN clients lookup the new address.
            #
            if [ -x /usr/sbin/dnsmasq ] ; then
                if [ -e /var/run/dnsmasq.pid ]; then

                    logMessage Allowing DNSMasq to restart.
                    kill -s HUP `cat /var/run/dnsmasq.pid`
                fi
            fi
        fi
    fi
fi


#
#  Log our finish
#
log_msg info "Script $0 finished"
