#!/bin/sh
#
#  This script ensures /etc/securetty upon the new guests has the new
# Xen console devices in it
#
# Steve
# --
# https://steve.fi/


prefix=$1


#
#  Source our common functions
#

if [ -e /usr/share/vm-deploy/common.sh ]; then
    . /usr/share/vm-deploy/common.sh
else
    . "${HOOK_DIR}/common.sh"
fi


#
# Log our start
#
log_msg "Script $0 starting"

#
# If the file doesn't exist exit early.
#
if [ ! -e ${prefix}/etc/securetty ]; then
    log_msg warn "/etc/securetty not found."
    exit
fi


#
#  Do both the devices.
#
for i in xvc0 hvc0 ; do
    #
    #  Only append if not presnt.
    #
    if ( grep $i ${prefix}/etc/securetty > /dev/null ) ; then
        log_msg info "Host already has $i entry"
    else
        echo $i >> ${prefix}/etc/securetty
    fi
done


#
# Log our finish
#
log_msg info "Script $0 finished."
